version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      # Remplacez par votre vrai token Hugging Face (commence par hf_)
      # Obtenez-le sur: https://huggingface.co/settings/tokens
      - HUGGINGFACE_API_TOKEN=hf_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx