version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./media:/app/media
      - ./db.sqlite3:/app/db.sqlite3
    environment:
      - DEBUG=False
      - SECRET_KEY=your-secret-key-here
      - HUGGINGFACE_API_TOKEN=your-huggingface-token-here
    restart: unless-stopped