version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./media:/app/media
      - ./db.sqlite3:/app/db.sqlite3
    environment:
      - DEBUG=False
      - SECRET_KEY=your-secret-key-here
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped

  # Alternative CPU-only version (uncomment if no GPU available)
  # web-cpu:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.cpu
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./media:/app/media
  #     - ./db.sqlite3:/app/db.sqlite3
  #   environment:
  #     - DEBUG=False
  #     - SECRET_KEY=your-secret-key-here
  #   restart: unless-stopped