# Generated by Django 5.1.4 on 2025-08-07 10:02

import txt2img.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(help_text='Text prompt used to generate the image')),
                ('image', models.ImageField(blank=True, null=True, upload_to=txt2img.models.image_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generation_time', models.FloatField(blank=True, help_text='Time taken to generate in seconds', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
